### PR TITLE
YearnUSDCStrategy

### PR DESCRIPTION
**Pull request by devneser**

### CODE REVIEW

**Comment by 0xPilot** [comment]
No need to implement Yearn Vault features on our contracts.
Please remove the mint feature when depositing tokens.
What we need for this strategy is to deposit/withdraw USDC to/from Yearn USDC Vault and returns TVL of this strategy.

**Comment by 0xSolcroot** [comment]
No need to implement Yearn Vault features on our contracts.
Please remove the mint feature when depositing tokens.
What we need for this strategy is to deposit/withdraw USDC to/from Yearn USDC Vault and returns TVL of this strategy.

**Comment by zingleton** [comment]
Yes. We are not creating any tokens with strategies. It seems that we did not communicate the goal and the interface of a strategy correctly. We need to have much more discussion about the requirements for "strategies". We should look at the treasury strategy for a simple example. How should we have this conversation?

**Review by 0xSolcroot — COMMENTED** [review]
1) Make the contract upgradeable
2) `require` statements - please try to use the short & proper comments.
3) _withdraw() function - the first parameter is wrong. It should be USD amount to withdraw, not `shares`. You will need to calculate the `shares` corresponding USD amount based on pricePerShare(). And return the withdrawn shares.

**Review by 0xSolcroot — APPROVED** [review]
LGTM

**Pull request merged**
